SklepKompMVC/SklepKompMVC/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SklepKompMVC.DAL;
using SklepKompMVC.Models;

namespace SklepKompMVC.Controllers
{
    public class AdminController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Admin
        public ActionResult Index()
        {
            return View(db.Orders.ToList());
        }

        // GET: Admin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderId,UserDataId,OrderHistoryId,FirstName,LastName,Address,City,AddresCode,PhoneNumber,Email,Comment,DateCreated,OrderState,TotalPrice")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(order);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId,UserDataId,OrderHistoryId,FirstName,LastName,Address,City,AddresCode,PhoneNumber,Email,Comment,DateCreated,OrderState,TotalPrice")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SklepKompMVC/SklepKompMVC/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SklepKompMVC.DAL;
using SklepKompMVC.Models;

namespace SklepKompMVC.Controllers
{
    public class CategoryController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Category
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Category/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryId,CategoryName,CategoryDescription,CatIconFileName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryId,CategoryName,CategoryDescription,CatIconFileName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SklepKompMVC/SklepKompMVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SklepKompMVC.DAL;
using SklepKompMVC.Models;

namespace SklepKompMVC.Controllers
{
    public class ProductController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Product
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category).Include(p => p.Producer);
            return View(products.ToList());
        }

        // GET: Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
            ViewBag.ProducerId = new SelectList(db.Producers, "ProducerId", "ProducerShortName");
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,CategoryId,ProductName,ProductDescription,ProducerId,DateAdded,ProductCoverFileName,Price,IsHidden,IsBestseller")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewBag.ProducerId = new SelectList(db.Producers, "ProducerId", "ProducerShortName", product.ProducerId);
            return View(product);
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewBag.ProducerId = new SelectList(db.Producers, "ProducerId", "ProducerShortName", product.ProducerId);
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,CategoryId,ProductName,ProductDescription,ProducerId,DateAdded,ProductCoverFileName,Price,IsHidden,IsBestseller")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewBag.ProducerId = new SelectList(db.Producers, "ProducerId", "ProducerShortName", product.ProducerId);
            return View(product);
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SklepKompMVC/SklepKompMVC/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SklepKompMVC.DAL;

namespace SklepKompMVC.Controllers
{
    public class StoreController : Controller
    {
        StoreContext Db = new StoreContext();
        // GET: Store
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var product = Db.Products.Find(id);
            return View(product);
        }

        public ActionResult List(string categoryname)
        {
            var category = Db.Categories.Include("Products").Where(g => g.CategoryName.ToUpper() == categoryname.ToUpper()).Single();
            var products = category.Products.ToList();

            return View(products);
        }
        [OutputCache(Duration = 80000)]
        [ChildActionOnly]
        public ActionResult CategoriesMenu()
        {
            var categories = Db.Categories.ToList();

            return PartialView("_CategoriesMenu", categories);
        }
    }
}

SklepKompMVC/SklepKompMVC/Views/Shared/_AdminLayout.cshtml
@{
    ViewBag.Title = ViewBag.Title;
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
}


<div class="col-md-3">
    @Html.Partial("_AdminMenuPartial")
</div>

<div class="col-md-9">
    @RenderBody()
</div>

SklepKompMVC/SklepKompMVC/Views/Shared/_AdminMenuPartial.cshtml
<ul class="list-group">

    <li class="list-group-item">
        <a href="@Url.Action("Index","Admin")">
            Zamówienia
        </a>
    </li>
    <li class="list-group-item">
        <a href="@Url.Action("Index","Category")">
            Kategorie
        </a>
    </li>
    <li class="list-group-item">
        <a href="@Url.Action("Index","Product")">
            Produkty
        </a>
    </li>
    <li class="list-group-item">
        <a href="@Url.Action("Index","Producer")">
            Producenci
        </a>
    </li>
    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        <li class="list-group-item">
            <a href="@Url.Action("UserRoleChange","Admin")">
                Uprawnienia użytkowników
            </a>
        </li>
    }
</ul>

SklepKompMVC/SklepKompMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>

                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>

        <div class="jumbotron">
            <h1 class="text-center">InFamous Sklep</h1>
            <img src="@Url.Content("~/Content/Images/spodigly-logo-main.png")" class="" />
        </div>

    </header>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SklepKompMVC/SklepKompMVC/Views/Shared/_NavbarMenu.cshtml
@model SklepKompMVC.ViewModel.HomeViewModel
@using SklepKompMVC.Infrastructure

<ul class="dropdown-menu">
    @foreach (var item in Model.Categories)
    {
        <li>
            <a @*style="background: no-repeat ; background-image: url(@Url.CategoryIconsPath(item.CatIconFileName));"*@
               href="@Url.Action("List","Store", new { categoryname = item.CategoryName.ToLower() } )">
                @item.CategoryName
            </a>
        </li>
    }
</ul>

SklepKompMVC/SklepKompMVC/Views/Shared/_ProfileMenu.cshtml
<ul class="list-group">

    <li class="list-group-item">
        <a href="@Url.Action("Index","Profile")">
            Profil
        </a>
    </li>
    <li class="list-group-item">
        <a href="@Url.Action("OrderHistory","Profile")">
            Zamówienia
        </a>
    </li>
    <li class="list-group-item">
        <a href="@Url.Action("Index","Manage")">
            Edytuj Dane
        </a>
    </li>
    @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Manager")))
    {
        <li class="list-group-item">
            <a href="@Url.Action("Index","Admin")">
                Panel Administratora
            </a>
        </li>
    }


</ul>

SklepKompMVC/SklepKompMVC/Views/Shared/_StoreLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Witamy w naszym sklepie</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    <header>
        <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#3c3c67">
            <div class="container">
                <div class="navbar-header" >
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Sklep InFamous", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Produkty <span class="caret"></span></a>
                           
                                @Html.Action("NavbarMenu", "Home")
                                
                              
                                
                            
                        </li>

                        @*<li>@Html.ActionLink("Produkty", "Index", "Home")</li>*@
                        @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                        @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div  class="container">
            <div class="jumbotron">
                <h1 class="text-center">InFamous Sklep</h1>
                @*<img src="@Url.Content("~/Content/Images/if-logo-main.png")" class="center-block" />*@
            </div>
        </div>
    </header>


    <div class="container body-content">


        @RenderBody()
       

    </div>    
    <hr />
        <footer>
            <div class="container">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="span2 col-md-3" >
                            <ul class="unstyled">
                                
                                InFamous
                                @Html.ActionLink("Produkty", "AdminPages", "Home", new { controllername = "Product" }, null)
                                <li>
                                    @Html.ActionLink("O Nas", "StaticContent","Home", new { viewname = "About" },null)
                               
                                </li>
                                <li>@Html.ActionLink("Kontakt", "StaticContent", "Home", new { viewname = "Contact" }, null)</li>
                                <li>@Html.ActionLink("Regulamin", "StaticContent", "Home", new { viewname = "Regulamin" }, null)</li>
                                
                            </ul>
                        </div>
                        <div class="span2 col-md-3">
                            <ul class="unstyled">
                                Użytkownik
                                <li><a href="#">Koszyk</a></li>
                                <li><a href="#">Zamówienia</a></li>
                                <li><a href="#">Konto</a></li>

                                
                                
                            </ul>
                        </div>
                        <div class="span2 col-md-3">
                            <ul class="unstyled">
                                Sklep
                                <li><a href="#">Produkty</a></li>
                                <li><a href="#">Home</a></li>
                                
                            </ul>
                        </div>
                        
                    </div>
                    <div class="col-md-3">  <p>&copy; @DateTime.Now.Year - Sklep InFamous</p></div>

                </div>
                
            </div>


        </footer>
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>